---
# Charts release configuration file example
# This file is used to update the version of the helm charts and images in the values.yaml file
# It is used in the charts-values-update-config action
# ${tag} is replaced with the tag/release version provided in the workflow

charts:
  - name: module1
    chart_file: charts/helm/module1/Chart.yaml
    values_file: charts/helm/module1/values.yaml
    image:
      - ghcr.io/${owner}/module1:${tag} # This will replace the image version with the tag/release version
      - ghcr.io/${owner}/module1-service1:${tag}-${THIRD_PARTY_VERSION} # This will replace the image version with the tag/release version and append the THIRD_PARTY_VERSION variable
      - ghcr.io/${owner}/module1-service2:#5\.\d+\.\d+ # This will select the latest tag matching the Python re regular expression
      - ghcr.io/${owner}/module1-service2:#latest # This will select the latest SemVer tag
